/** Hierarchical error codes for storage module (Rule XXII) */
export const STORAGE_ERRORS = {
  // Provider errors
  PROVIDER_UNAVAILABLE: 'storage.provider.unavailable',
  PROVIDER_AUTH_FAILED: 'storage.provider.auth_failed',
  PROVIDER_QUOTA_EXCEEDED: 'storage.provider.quota_exceeded',
  PROVIDER_UNKNOWN: 'storage.provider.unknown',

  // File operation errors
  UPLOAD_FAILED: 'storage.file.upload_failed',
  DOWNLOAD_FAILED: 'storage.file.download_failed',
  DELETE_FAILED: 'storage.file.delete_failed',
  NOT_FOUND: 'storage.file.not_found',
  SIGNED_URL_FAILED: 'storage.file.signed_url_failed',

  // Validation errors
  FILE_TOO_LARGE: 'storage.validation.file_too_large',
  MIME_NOT_ALLOWED: 'storage.validation.mime_not_allowed',
  MIME_MISMATCH: 'storage.validation.mime_mismatch',
  EMPTY_FILE: 'storage.validation.empty_file',
  INVALID_FILENAME: 'storage.validation.invalid_filename',

  // Rollback
  ROLLBACK_FAILED: 'storage.rollback.cleanup_failed',

  // Hard delete (purge job only)
  HARD_DELETE_FAILED: 'storage.hard_delete_failed',

  // Event emission (warning-level, not returned to callers)
  EVENT_PUBLISH_FAILED: 'storage.event.publish_failed',
} as const;

// Note: Attachment CRUD error codes (create_failed, not_found, etc.)
// are auto-generated by BaseRepository using the moduleName 'storage'
// (e.g., 'storage.create_failed', 'storage.not_found').
// Do NOT duplicate them here.
